---
- name: optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install websvn packages
  ansible.builtin.include_tasks: packages.yml
  when: websvn__manage_packages | bool

- name: websvn users
  ansible.builtin.include_tasks: user.yml
  when: websvn__adduser | bool

- name: setup php pear stuff
  ansible.builtin.include_tasks: pear_setup.yml
  when: not websvn__skip_peap | bool

- name: install websvn
  become: true
  ansible.builtin.package:
    name: "{{ websvn__packages }}"
    state: "{{ websvn__state }}"
  register: websvn
  ignore_errors: true

- name: install websvn manually
  ansible.builtin.include_tasks: manual_install_websvn.yml
  when: websvn.failed | bool
