---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: packages.yml
  when: websvn__manage_packages | bool

- include_tasks: user.yml
  when: websvn__adduser | bool

- include_tasks: pear_setup.yml
  when: not websvn__skip_peap | bool
- name: install websvn
  become: true
  package:
    name: "{{ websvn__packages }}"
    state: "{{ websvn__state }}"
  register: websvn
  ignore_errors: true

- include_tasks: manual_install_websvn.yml
  when: websvn.failed | bool
